# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Utilisation d'Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"
  
  # Configuration du nom de la VM
  config.vm.hostname = "docker-app"
  
  # Configuration réseau - Port forwarding pour accéder à l'application
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  
  # Configuration de la VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-app-vm"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  # Synchronisation du dossier du projet
  config.vm.synced_folder ".", "/vagrant"
  
  # Provisioning avec Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventory"
    ansible.verbose = "v"
  end
end
