
# Configuration des serveurs web
- hosts: serveurs_web
  become: yes

  tasks:
    - name: Install Apache and dependencies
      apt:
        name:
          - apache2
        state: present
        update_cache: yes

    - name: Create /var/www/toto directory
      file:
        path: /var/www/toto
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create simple web page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Page Web Simple</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 50px; }
              h1 { color: #333; }
            </style>
          </head>
          <body>
            <h1>Bienvenue sur le serveur web</h1>
            <p>Cette page est servie par {{ ansible_hostname }}</p>
            <p>Adresse IP: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: /var/www/toto/toto.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure Apache to serve from /var/www/toto
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create Apache configuration for toto
      copy:
        content: |
          <VirtualHost *:80>
            ServerName localhost
            DocumentRoot /var/www/toto
            <Directory /var/www/toto>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>
        dest: /etc/apache2/sites-available/toto.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable toto Apache site
      shell: |
        a2dissite 000-default.conf || true
        a2ensite toto.conf
      notify: restart apache

    - name: Verify Apache is enabled
      systemd:
        name: apache2
        enabled: yes

    - name: Ensure Apache service started
      systemd:
        name: apache2
        state: started

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted

# Configuration de la base de données
- hosts: base_donnees
  become: yes

  tasks:
    - name: Install MariaDB server
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present
        update_cache: yes

    - name: Ensure MariaDB service is enabled
      systemd:
        name: mariadb
        enabled: yes

    - name: Ensure MariaDB service is started
      systemd:
        name: mariadb
        state: started

    - name: Allow network access to MariaDB
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      notify: restart mariadb

  handlers:
    - name: restart mariadb
      systemd:
        name: mariadb
        state: restarted