# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"
  
  # Configuration de la VM
  config.vm.hostname = "docker-dev"
  
  # Configuration réseau
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Forwarding de ports pour Docker
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  
  # Configuration VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-dev"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  # Synchronisation des dossiers
  config.vm.synced_folder ".", "/vagrant"
  
  # Provisioning avec Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"
  end
end
