Vagrant.configure("2") do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.insert_key = false # to use the global unsecure key instead of one insecure key per VM
    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end

    config.vm.define :app1 do |app1|
      # Vagrant va récupérer une machine de base ubuntu 20.04 (focal) depuis cette plateforme https://app.vagrantup.com/boxes/search
      app1.vm.box = "bento/ubuntu-24.04"
      app1.vm.hostname = "app1"
      app1.vm.network :private_network, ip: "192.168.56.111"
    end

    config.vm.define :app2 do |app2|
      # Vagrant va récupérer une machine de base ubuntu 20.04 (focal) depuis cette plateforme https://app.vagrantup.com/boxes/search
      app2.vm.box = "bento/ubuntu-24.04"
      app2.vm.hostname = "app2"
      app2.vm.network :private_network, ip: "192.168.56.112"
    end
  end